on:
  push:
    branches:
      - dev

name: File Upload Test

jobs:
  phpunit:
    runs-on:  ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install
      
      -name: Run Application Test Suite
        run: make